# Generated by Django 3.2.3 on 2021-05-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_auto_20210527_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='imagem',
            new_name='thumbnailDetail',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='thumbnail',
            new_name='thumbnailHome',
        ),
    ]
