# Generated by Django 3.2.3 on 2021-06-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_auto_20210527_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='projlink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
