# Generated by Django 3.1 on 2021-07-31 15:10

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_projeto_projlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True),
        ),
        migrations.AlterField(
            model_name='tecnologias',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
